=== johannes-tenschert/itil-triggers-interfaces/raw/triggers.dtd
<!ELEMENT book (name, process*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT process (name, trigger+)>
<!ELEMENT trigger (#PCDATA | class | tex | trigger)*>
<!ATTLIST trigger
	page CDATA #REQUIRED
>
<!ELEMENT class (#PCDATA | force | tex )*>
<!ATTLIST class
	type CDATA #REQUIRED
>
<!ELEMENT force (assertive?, commissive?, declarative?, directive?, expressive?)>
<!ATTLIST force
	name CDATA #REQUIRED
>
<!ELEMENT assertive EMPTY>
<!ELEMENT commissive EMPTY>
<!ELEMENT declarative EMPTY>
<!ELEMENT directive EMPTY>
<!ELEMENT expressive EMPTY>
<!ELEMENT tex (#PCDATA)>

=== johannes-tenschert/itil-triggers-interfaces/raw/ServiceStrategy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "triggers.dtd">
<book>
	<name>Service Strategy</name>

	<process>
		<name>Strategy Management for IT services</name>
		<trigger page="166"><class type="periodic">Annual planning cycles</class> Strategy management for IT services is used to review and plan on an annual basis</trigger>
		<trigger page="166"><class type="observation">New business opportunity</class> Strategy management for IT services is used to analyze, set objectives, perspectives, positions, plans and patterns for new business or service opportunities.</trigger>
		<trigger page="166"><class type="observation">Changes to internal or external environments</class> Strategy management for IT services will assess the impact of environmental changes on the existing strategic and tactical plans.</trigger>
		<trigger page="166"><class type="decision">Mergers or acquisitions</class> The merger with or acquisition of another company will trigger a detailed analysis and definition of the strategy of the new organization.</trigger>
	</process>

	<process>
		<name>Service Portfolio Management</name>
		<trigger page="196"><class type="speechact"><force name="Inform"><assertive/><directive/></force>A new strategy has been devised, or an existing strategy is being changed</class>. This does not necessarily have to be in the form of a plan before service portfolio management is involved. A change to a perspective, position or pattern of action might impact existing services or service models. Service portfolio management could be used as part of the analysis of any potential impact.</trigger>
		<trigger page="196"><class type="speechact"><force name="Request"><directive/></force>Business relationship management receives a request for a new service or a change to an exisiting service</class>. Service portfolio management helps to define and formalize this request before <class type="none">submitting it to change management</class> in the form of a <class type="none">change proposal</class></trigger>
		<trigger page="196"><class type="decision">Service improvement opportunities from CSI</class></trigger>
		<trigger page="196"><class type="speechact"><force name="Inform"><assertive/></force><force name="Warn"><directive/></force><force name="Complain"><assertive/><directive/><expressive/></force><force name="Recommend"><directive/></force>Feedback from design, build and transition teams to indicate the status of the service during the charter stage of the process</class>. If these reports indicate a deviation from the specifications, cost or release time, service portfolio management will be involved in estimating the impact of this, and defining corrective action.</trigger>
		<trigger page="196"><class type="speechact"><force name="Review"><assertive/><directive/></force>Service level management reviews that identify a service is not meeting its expected outcomes or that it is not being used in the way it was intended</class>.</trigger>
		<trigger page="196"><class type="speechact"><force name="Warn"><directive/></force>Financial management for IT services indicates that a service costs significantly more or less than anticipated</class>, thus impacting the potential return on investment for that service.</trigger>
	</process>

	<process>
		<name>Financial Management for IT Services</name>
		<trigger page="240"><class type="periodic">Monthly, quarterly and annual financial reporting cycles</class> are mandated and form part of the standard financial management policies and standards of any organization. An example of a regularly triggered financial process is budgeting.</trigger>
		<trigger page="240"><class type="artifact">Audits will indicate actions</class> that need to be taken to adjust some aspect of the accounting, budgeting or charging system.</trigger>
		<trigger page="240"><class type="speechact"><force name="Request"><directive/></force>Requests for financial information from other service management processes</class> - for example, return on investment information for services in the service portfolio, or information to determine the cost of making a change.</trigger>
		<trigger page="240"><class type="decision">Investigation into a new service opportunity</class>, either during the definition of a strategy (high-level financial value of the opportunity), <class type="none">or during service portfolio management</class> where a more specific financial assessment is required.
			<tex>\\ \textcolor{red}{\small $\rightarrow$</tex> SPM primarily triggered by speech acts, nonetheless it's a decision that is communicated<tex>}</tex></trigger>
		<trigger page="240"><class type="decision">The introduction of charging for IT services</class> (internal service provider) or the need to determine the price of a service (external service provider).</trigger>
		<trigger page="240"><class type="speechact"><force name="Request"><directive/></force>A request for change</class> will trigger the need for financial information about the cost of making changes, and the ongoing financial impact of the change.</trigger>
	</process>

	<process>
		<name>Demand Management</name>
		<trigger page="253"><class type="speechact"><force name="Request"><directive/></force>A request from a customer for new service, or change to an existing service</class>. This will be initiated through business relationship management and service portfolio management.</trigger>
		<trigger page="253"><class type="decision">A new service is being created to meet a strategic initiative</class> - this will be initiated through service portfolio management.</trigger>
		<trigger page="253"><class type="decision">A service model needs to be defined</class>, and patterns of business activity and/or user profiles must be defined.</trigger>
		<trigger page="253"><class type="artifact">Utilization rates are causing potential performance issues</class>, or a potential breach of an SLA</trigger>
		<trigger page="253"><class type="artifact">An exception has occured</class> to forecast patterns of business activity</trigger>
	</process>

	<process>
		<name>Business Relationship Management</name>
		<trigger page="277"><class type="decision">A new strategic initiative</class></trigger>
		<trigger page="277"><class type="decision">A new service, or a change to an existing service, has been initiated</class></trigger>
		<trigger page="277"><class type="observation">A new opportunity has been identified</class></trigger>
		<trigger page="277"><class type="decision">A service has been chartered</class> by service portfolio management</trigger>
		<trigger page="277"><class type="speechact"><force name="Request"><directive/></force><force name="Suggest"><directive/></force>Customer requests or suggestions</class></trigger>
		<trigger page="277"><class type="speechact"><force name="Complain"><assertive/><directive/><expressive/></force>Customer complaints</class></trigger>
		<trigger page="277"><class type="artifact">A customer meeting has been scheduled</class></trigger>
		<trigger page="277"><class type="artifact">A customer satisfaction survey has been scheduled</class></trigger>
	</process>
</book>

=== johannes-tenschert/itil-triggers-interfaces/raw/ServiceOperation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "triggers.dtd">
<book>
	<name>Service Operation</name>

	<process>
		<name>Event Management</name>
		<trigger page="69"><class type="system event">Exceptions to any level of CI performance defined in the design specifications, OLAs or SOPs</class></trigger>
		<trigger page="69"><class type="system event">Exceptions to an automated procedure or process, e.g. a routine change that has been assigned to a build team has not been completed in time</class></trigger>
		<trigger page="69"><class type="system event">An exception within a business process that is being monitored by event management</class></trigger>
		<trigger page="69"><class type="artifact">The completion of an automated task or job</class></trigger>
		<trigger page="69"><class type="system event">A status change in a server or database CI</class></trigger>
		<trigger page="69"><class type="system event">Access of an application or database by a user or automated procedure or job</class></trigger>
		<trigger page="70"><class type="system event">A situation where a device, database or application etc. has reached a predefined threshold of performance.</class></trigger>
	</process>

	<process>
		<name>Incident Management</name>
		<trigger page="83"><class type="speechact"><force name="Notify"><assertive/></force><force name="Request"><directive/></force><force name="Complain"><assertive/><directive/><expressive/></force>Common: User rings the service desk or completes a web-based incident-logging screen</class></trigger>
		<trigger page="83"><class type="system event">Incidents raised automatically via event management tools</class></trigger>
		<trigger page="83"><class type="speechact"><force name="Notify"><assertive/></force><force name="Warn"><directive/></force>Potential failures noticed by technical staff</class></trigger>
		<trigger page="83"><class type="speechact"><force name="Notify"><assertive/></force><force name="Warn"><directive/></force>Initiation of suppliers</class></trigger>
	</process>

	<process>
		<name>Request Fulfilment</name>
		<trigger page="94"><class type="speechact"><force name="Request"><directive/></force>User calling the service desk</class></trigger>
		<trigger page="94"><class type="speechact"><force name="Request"><directive/></force>User completing some form of self-help web-based input screen</class></trigger>
	</process>

	<process>
		<name>Problem Management</name>
		<trigger page="106"><class type="artifact">Reaction to one or more incidents</class></trigger>
		<trigger page="106"><class type="speechact"><force name="Initiate"><directive/></force>Raised/initiated via service desk staff</class></trigger>
		<trigger page="106"><class type="speechact"><force name="Notify"><assertive/></force><force name="Warn"><directive/></force>Testing (particularly the latter stages of testing, user acceptance testing)</class></trigger>
		<trigger page="106"><class type="speechact"><force name="Notify"><assertive/></force><force name="Warn"><directive/></force>Suppliers (potential faults / known deficiencies in their products or services)</class></trigger>
		<trigger page="106"><class type="artifact">Proactive: By patterns of incidents, operation logs, operation communications, event logs</class></trigger>
	</process>

	<process>
		<name>Access Management</name>
		<trigger page="115"><class type="speechact"><force name="Request"><directive/></force>An RFC (large-scale service introductions / upgrades)</class></trigger>
		<trigger page="115"><class type="speechact"><force name="Request"><directive/></force>A service request (service desk)</class></trigger>
		<trigger page="115"><class type="speechact"><force name="Request"><directive/></force>A request from human resources</class></trigger>
		<trigger page="115"><class type="speechact"><force name="Request"><directive/></force>A request from a manager</class></trigger>
	</process>
</book>

=== johannes-tenschert/itil-triggers-interfaces/raw/ContinualServiceImprovement.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "triggers.dtd">
<book>
	<name>Continual Service Improvement</name>

	<process>
		<name>Continual Service Improvement Processes</name>
		<trigger page="64">Ongoing processes:<trigger page="64"><class type="periodic">Probably periodic triggers</class></trigger><trigger page="64"><class type="observation">Probably observations by continual service improvement staff</class></trigger></trigger>
		<trigger page="64"><class type="decision">New incentives</class></trigger>
		<trigger page="64"><class type="decision">Changing business requirements</class>
			<tex>\\ $\rightarrow$</tex> Highly probable due to decision to accept / for awareness of changed requirements</trigger>
		<trigger page="64">Poor performance or spiralling costs:<trigger page="64"><class type="speechact"><force name="Complain"><assertive/><directive/><expressive/></force>Complaint</class></trigger><trigger page="64"><class type="artifact">Automatically gathered information</class></trigger></trigger>
	</process>
</book>

=== johannes-tenschert/itil-triggers-interfaces/raw/ServiceTransition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book SYSTEM "triggers.dtd">
<book>
	<name>Service Transition</name>

	<process>
		<name>Transition Planning and Support</name>
		<trigger><class type="speechact"><force name="Authorize"><declarative /></force>Authorized change</class> (<tex>$\rightarrow$</tex> Planning a single transition)</trigger>
		<trigger><class type="speechact"><force name="Inform"><assertive/><directive/></force>Receipt of a change proposal from service portfolio management</class> (<tex>$\rightarrow$</tex> Longer-term planning)</trigger>
		<trigger><class type="periodic">The organization&apos;s budgetary planning cycle</class> (<tex>$\rightarrow$</tex> budgeting for future transition requirements)</trigger>
	</process>

	<process>
		<name>Change Management</name>
		<trigger><class type="decision">Strategic changes</class><trigger>Legal / regulatory change</trigger><trigger>Organizational change</trigger><trigger>Policy and standards change</trigger><trigger>Change after analyzing business, customer and user activitiy patterns</trigger><trigger>Addition of new service to the market space</trigger><trigger>Updates to the service portfolio, customer portfolio or customer agreement portfolio</trigger><trigger>Change of sourcing model</trigger><trigger>Technology innovation</trigger>
		</trigger>
		<trigger><class type="decision">Change to one or more services</class><trigger>Service catalogue</trigger><trigger>Service package</trigger><trigger>Service definition and characteristics</trigger><trigger>Release package</trigger><trigger>Capacity and resource requirements</trigger><trigger>...</trigger></trigger>
		<trigger>Operational change: Requests initiated by users<trigger><class type="speechact"><force name="Request"><directive/></force>Password reset</class></trigger><trigger><class type="speechact"><force name="Request"><directive/></force>Access request</class></trigger><trigger><class type="speechact"><force name="Request"><directive/></force>Request to move an IT asset</class></trigger></trigger>
		<trigger>Changes to deliver continual improvement<trigger><class type="none">CSI determines</class> that an improvement to a service is warranted <tex>$\rightarrow$</tex><class type="speechact"><force name="Request"><directive/></force>RFC submitted to change management</class></trigger></trigger>
	</process>

	<process>
		<name>Service Asset and Configuration Management</name>
		<trigger><class type="speechact"><force name="Notify"><assertive/></force><force name="Authorize"><declarative /></force><force name="Reject"><declarative/></force>Updates from change management</class> (see Figure 4.6)<tex>\\</tex>
			e.g. Raise/record change request, Authorize/reject change, Close change</trigger>
		<trigger><class type="speechact"><force name="Notify"><assertive/></force>Updates from release and deployment management</class></trigger>
		<trigger><class type="speechact"><force name="Order"><directive/></force>Purchase orders</class></trigger>
		<trigger><class type="decision">Acquisitions</class></trigger>
		<trigger><class type="speechact"><force name="Request"><directive/></force>Service requests</class></trigger>
	</process>

	<process>
		<name>Release and deployment management</name>
		<trigger><class type="speechact"><force name="Authorize"><declarative /></force>Receipt of an authorized change to plan, build and test a production-ready release package</class>
			<tex>\\ $\rightarrow$</tex> Release and deployment management</trigger>
		<trigger><class type="speechact"><force name="Authorize"><declarative /></force>Receipt of an authorized change to deploy a release package</class> to a target deployment group or environment (e.g. business unit, customer group) <tex>\\ $\rightarrow$</tex> Deployment</trigger>
	</process>

	<process>
		<name>Service Validation and Testing</name>
		<trigger><class type="artifact">Scheduled activity on a release plan, test plan or quality assurance plan</class></trigger>
	</process>

	<process>
		<name>Change Evaluation</name>
		<trigger><class type="speechact"><force name="Request"><directive/></force>Receipt of a request for evaluation from change management</class></trigger>
	</process>

	<process>
		<name>Knowledge Management</name>
		<trigger><class type="speechact"><force name="Inform"><assertive/></force>Business relationship management storing the minutes of a customer meeting</class>
			<tex>\\ {\small ($\rightarrow$</tex>Storing commitments, questions, ...<tex>)}</tex></trigger>
		<trigger><class type="decision">Updates to the service catalogue or service portfolio</class></trigger>
		<trigger><class type="decision">Modification of a service design package</class></trigger>
		<trigger><class type="decision">Creation of a new or updated capacity plan</class></trigger>
		<trigger><class type="artifact">Receipt of an updated user manual from a supplier</class>
			<tex>\\ {\small ($\rightarrow$</tex> Artifact or informing about artifact... Decision: just artifact<tex>)}</tex></trigger>
		<trigger><class type="artifact">Creation of a customer report</class></trigger>
		<trigger><class type="decision">Updates to the CSI register</class></trigger>
	</process>
</book>
